version: '3.8'

services:
  ai-bark-app:
    build: .
    container_name: ai-bark-system
    ports:
      - "5050:5000"
    environment:
      # 数据库配置
      - DATABASE_URL=sqlite:////app/data/scripts.db
      
      # Gemini API配置（请替换为您的API Key）
      - GEMINI_API_KEY=YOUR_GEMINI_API_KEY
      
      # Bark配置（请替换为您的Device Key）
      - BARK_DEVICE_KEY=YOUR_BARK_DEVICE_KEY
      
      # 可选：自定义Bark服务器
      # - BARK_API_SERVER=https://your-bark-server.com
    
    volumes:
      - ./data:/app/data
      # - ./scripts:/app/scripts
    
    restart: unless-stopped